# Generated by Django 3.1.5 on 2021-01-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can like book', 'can_like_book'), ('can unlike book', 'can_unlike_book')]},
        ),
    ]
